name: IgnitedPotions
description: A re-model of minecraft's brewing, with permissions, new effects, and custom modifiers.
author: IBeHunting
version: v1.2.1-beta
api-version: 1.8.8
main: io.github.IBeHunting.IgnitedPotions.PotionsPlugin

commands:
  potions:
    description: Main potions plugin command
    usage: /potions [reload | save | view]
  givepotion:
    description: Give a player a custom potion
    permission: potions.admin
    permission-message: ยง4You do not have access to that command.
    usage: /givepotion [player] [type] [tier] [extended] [splash]

permissions:
  potions.admin:
    description: Load/Save/Give permissions
    default: op
    children:
  potions.brew.*:
    description: Brew all potions
    default: op
    children:
      potions.brew.haste: true
      poitons.brew.mining_fatigue: true
      potions.brew.absorption: true
      potions.brew.health_boost: true
      potions.brew.nausea: true
      potions.brew.blindness: true
      potions.brew.resistance: true
      potions.brew.saturation: true
      potions.brew.hunger: true
      potions.brew.wither: true
      potions.brew.strength: true
      potions.brew.speed: true
      potions.brew.fire_resistance: true
      potions.brew.instant_health: true
      potions.brew.jump_boost: true
      potions.brew.regeneration: true
      potions.brew.poison: true
      potions.brew.water_breathing: true
      potions.brew.night_vision: true
      potions.brew.weakness: true
      potions.brew.invisibility: true
      potions.brew.instant_damage: true
      potions.brew.slowness: true

  potions.brew.haste:
    default: op
  potions.brew.mining_fatigue:
    default: op
  potions.brew.absorption:
    default: op
  potions.brew.health_boost:
    default: op
  potions.brew.nausea:
    default: op
  potions.brew.blindness:
    default: op
  potions.brew.resistance:
    default: op
  potions.brew.saturation:
    default: op
  potions.brew.hunger:
    default: op
  potions.brew.wither:
    default: op
  potions.brew.strength:
    default: true
  potions.brew.speed:
    default: true
  potions.brew.fire_resistance:
    default: true
  potions.brew.instant_health:
    default: true
  potions.brew.jump_boost:
    default: true
  potions.brew.regeneration:
    default: true
  potions.brew.poison:
    default: true
  potions.brew.night_vision:
    default: true
  potions.brew.water_breathing:
    default: true
  potions.brew.weakness:
    default: true
  potions.brew.invisibility:
    default: true
  potions.brew.instant_damage:
    default: true
  potions.brew.slowness:
    default: true