name: IgnitedPotions
description: Adds more brewable potion types
author: IBeHunting
version: 1.0.1
api-version: 1.8.8
main: io.github.IBeHunting.IgnitedPotions.PotionsPlugin

commands:
  potions:
    description: Main potions plugin command
    usage: /potions [reload | save | view]
  givepotion:
    description: Give a player a custom potion
    permission: potions.admin
    permission-message: ยง4You do not have access to that command.
    usage: /givepotion [player] [type] [tier] [extended] [splash]

permissions:
  potions.admin:
    description: Load/Save/Give permissions
    default: op
    children:
  potions.brew.*:
    description: Brew all potions
    default: op
    children:
      potions.brew.haste: true
      poitons.brew.mining_fatigue: true
      potions.brew.absorption: true
      potions.brew.health_boost: true
      potions.brew.nausea: true
      potions.brew.blindness: true
      potions.brew.resistance: true
      potions.brew.saturation: true
      potions.brew.hunger: true
      potions.brew.wither: true
  potions.brew.haste:
    default: op
  potions.brew.mining_fatigue:
    default: op
  potions.brew.absorption:
    default: op
  potions.brew.health_boost:
    default: op
  potions.brew.nausea:
    default: op
  potions.brew.blindness:
    default: op
  potions.brew.resistance:
    default: op
  potions.brew.saturation:
    default: op
  potions.brew.hunger:
    default: op
  potions.brew.wither:
    default: op